Repository ist-bot-team/ist-discord-bot, pull requests merged in 2022-10, with the labels that each got.

#98 Fix course RSS link not being imported
  src/modules/courses.ts
  src/modules/degrees.ts
  src/modules/fenix.ts
  src/modules/rss.ts
Labels: bug

#99 Allow refreshing courses without specifying a degree
  src/modules/degrees.ts
Labels: enhancement

#72 Rewrite the bot in TypeScript (v2)
  .dockerignore
  .eslintrc.json
  .github/workflows/publish-docker-image.yml
  .gitignore
  .husky/.gitignore
  .husky/pre-commit
  .npmrc
  .prettierignore
  .prettierrc.json
  Dockerfile
  Dockerfile.dev
  LICENSE
  Procfile
  README.md
  bot.py
  courses_by_degree.json
  degrees.json
  embeds.json
  package.json
  requirements.txt
  self_roles.json
  src/bot.d.ts
  src/bot.ts
  src/logger.ts
  src/modules/courses.d.ts
  src/modules/courses.ts
  src/modules/degrees.ts
  src/modules/fenix.d.ts
  src/modules/fenix.ts
  src/modules/galleryChannels.ts
  src/modules/leaderboard.ts
  src/modules/misc.ts
  src/modules/polls.ts
  src/modules/roleSelection.ts
  src/modules/rss.ts
  src/modules/sudo.ts
  src/modules/utils.d.ts
  src/modules/utils.ts
  src/modules/welcome.ts
  src/prisma/migrations/20210815204238_init/migration.sql
  src/prisma/migrations/20210821102445_role_selection/migration.sql
  src/prisma/migrations/20210822093133_add_emoji_to_menu_opt/migration.sql
  src/prisma/migrations/20210822215809_add_channel_id_and_allow_multiselect_role_groups/migration.sql
  src/prisma/migrations/20210822221619_add_message_to_role_groups/migration.sql
  src/prisma/migrations/20210823191157_add_messageid_to_role_groups/migration.sql
  src/prisma/migrations/20210904233150_cascade_role_group_option/migration.sql
  src/prisma/migrations/20210919001905_add_leaderboard_entries/migration.sql
  src/prisma/migrations/20210919131102_rename_attendance_polls_to_polls/migration.sql
  src/prisma/migrations/20210919145235_make_poll_schedule_optional/migration.sql
  src/prisma/migrations/20211003144607_add_degree_course_features/migration.sql
  src/prisma/migrations/20211003151727_rss_announcements/migration.sql
  src/prisma/migrations/migration_lock.toml
  src/prisma/schema.prisma
  src/utils/buttonStyleUtils.ts
  tools/courses_scrapper.py
  tsconfig.json
  version
  yarn.lock
Labels: enhancement

#101 Add remove all courses buttons
  src/modules/courses.ts
  src/modules/roleSelection.ts
Labels: enhancement

#100 Add context menu command support
  src/bot.d.ts
  src/bot.ts
  src/modules/misc.ts
  src/modules/utils.ts
Labels: enhancement

#102 Add Just Ask context menu command
  src/modules/misc.ts
Labels: enhancement

#104 Fix incorrect role removal count
  src/modules/courses.ts
Labels: bug

#108 Rename `hideChannel` to snake case column for consistency
  src/prisma/migrations/20221022151322_hide_channel_name_consistency/migration.sql
  src/prisma/schema.prisma
Labels: bug

#109 Integrate `just-ask` with `who-said` and add `who-said` MessageContextMenuCommand
  src/modules/misc.ts
Labels: bug, enhancement

#114 Improve logging of gallery channels message handler
  README.md
  src/modules/galleryChannels.ts
Labels: enhancement

#115 Add CI, yarn build + prettier
  .github/workflows/typescript.yml
Labels: enhancement
